### ISSUE TITLE
Issue: Eclipse has no chance against Syzygy

### ISSUE THREAD

**Issue by mmmmaaaaarrrrrrkkkkkkkk** [eclipsechat/roadmap#1]
### ***#screweclipsesyzygyisbetter***

**Comment by mmmmaaaaarrrrrrkkkkkkkk** [comment]
nice try >:)

![image](https://github.com/user-attachments/assets/d435db2e-7bb7-4bbc-9526-604ffc320ca9)

**Comment by heyimtris** [comment]
syzygy doesnt have a roadmap so ha i'm better

**Comment by mmmmaaaaarrrrrrkkkkkkkk** [comment]
it does, just internally

**Comment by heyimtris** [comment]
no

**Comment by mmmmaaaaarrrrrrkkkkkkkk** [comment]
[_**yes**_
](https://syzygy.frctl.lol)

**Comment by heyimtris** [comment]
![image](https://github.com/user-attachments/assets/e3ccd22a-d9cd-4b57-b6e2-4b88ba4f576e)

**Comment by mmmmaaaaarrrrrrkkkkkkkk** [comment]
i'm late but you kinda need to be an admin to access it

you gave that up a while ago
